// BadgerFit - server.js
require('dotenv').config();
const express = require('express');
const cors = require('cors');
const path = require('path');

const app = express();

app.use(cors());
app.use(express.json());

// Serve all your HTML/CSS/JS files statically from the project root
app.use(express.static(path.join(__dirname)));

// Routes
app.use('/api/match', require('./routes/match'));
app.use('/api/gyms',  require('./routes/gyms'));

// Expose Maps API key to frontend safely
app.get('/api/maps-key', (req, res) => {
  res.json({ key: process.env.GOOGLE_PLACES_KEY });
});

// Serve locally stored gym images (generated by fetchImages.js)
// Usage: GET /api/gym-photo?placeId=ChIJ...
app.get('/api/gym-photo', (req, res) => {
  const { placeId } = req.query;
  if (!placeId) return res.status(400).json({ error: 'Missing placeId' });

  const imgPath = path.join(__dirname, 'images', `${placeId}.jpg`);

  if (require('fs').existsSync(imgPath)) {
    res.setHeader('Cache-Control', 'public, max-age=604800'); // 1 week
    return res.sendFile(imgPath);
  }

  // Image not found — send a generic gym fallback
  const FALLBACKS = [
    'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=700&h=400&fit=crop',
    'https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=700&h=400&fit=crop',
    'https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=700&h=400&fit=crop',
    'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=700&h=400&fit=crop',
    'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=700&h=400&fit=crop',
  ];
  const fallback = FALLBACKS[
    Math.abs(placeId.split('').reduce((a, c) => a + c.charCodeAt(0), 0)) % FALLBACKS.length
  ];
  res.redirect(fallback);
});

const PORT = 3000;
app.listen(PORT, () => {
  console.log(`✅ BadgerFit server running at http://localhost:${PORT}`);
});